# Discussion {#discussion}

Overall our study found no evidence of mesopredator release in the mouse populations we monitored. We used a Bayesian Hierarchical Model (BHM) to test our five predictions by experimentally manipulating ecosystem scale predator control to compare differences between `r #n.grid` areas with or without stoat control and a rat removal treatment on half our replicates. Our model replicated the mouse dynamics in our data and produced similar results to other NZ mammals community models (@choquenot2000; @ruscoe2001; @ruscoe2005; @tompkins2006; @tompkins2013; @holland2015; summarised in Figure 1). High food availability resulting in high mouse abundance is commonly observed in a range of NZ forest types [@innes; @sweetapple; @ruscoe2011; @ruscoe2012]. Modelling has incorporated these parameter estimates to represent invasive species dynamics in NZ forests [@tompkins2006; @tompkins2013; @holland2015] A naive investigation of our summarised data (Figure 3.1, 3.2, and 3.3) might have falsely lead to similarly low powered conclusions, that rats may have an effect on mice dynamics as well as many generally accepted relationships. By using a BHM framework we were able to test the theoretical relationships proposed using experimental data.

#### Seed avaliablilty

When we fit our community model to the replicated CR data we found that beech seed and the subsequent *intake rate* had the greatest impact on mice populations in all seasons. We found that $r_{j,t}$ was strongest on grid and trips when beech seed was increasing. After comparing a selection of functional responses to our data (Appendix 1.3) we found the best type II response and converted our estimated $Seed_{j,k}$ per $m^2$ to the "*intake rate*" $S_{j,t}$. We found that the effect of mouse density ($N_{j,t}$) and rats ($R_{j,t}$) was lower than the "*intake rate*" ($S_{j,t}$). We observed that the effects of density were greatest during the declining seasons. These differences in effect sizes are similar to other studies.

#### Mouse density

The effect of mouse density and rats on was much lower and were also similar to other published results [@choquenot2000]. We and many other studies observed high heterogeneity in abundance estimates. This type of data can be difficult to model correctly in many frequentest frameworks. To account for this heterogeneity in the biological data we used experimental manipulation and bayesian modelling framework to account for the confounding effects of food availability, mouse density, and rats to simultaneously assess the overall effect of stoat control on mice dynamics. Importantly, our model captured both the observational and process variability within NZ beech forests. We also conclude that the underlying heterogeneity in small mammal populations was sufficiently large to make estimating true response of mice to rats difficult in biological experiments (Figures 4-9).

#### Rat presence

Our results suggest that it is unlikely that rats have strong impacts on the rate of increase of mice in our large scale study system. Contrary to this, previous laboratory experiments suggested that interactions between mice and rats were negatively related to predation or competition effects and limited evidence of competition release has been observed in mixed podocarp-tawa forests in NZ. We found that rats had the smallest impact on mice dynamics (Figure 8). In part, this is due to the high variability in the number of rats and kiore between grids and sampling trips in our study (**??**), which is often the case in non-laboratory studies. Instead of rats/kiore being present but at low numbers in all grids (low effect size and low uncertainty), there were only a few grids that had comparability high numbers. This result suggests that refugee areas may exist and  can support larger rodents in beech forests that current averages suggest. Overall, it is likely that beech forests do not have enough resources to support larger spatially uniform populations of rats.

## Bayesian modelling

The application of BHM's in ecology has been increasing over the past decade [@king2012]. BHM modelling can provide challenges when selecting models and assessing model fit [@auger-methe2016]. To account for this, we used the general associations above as well as AIC and r-squared. We then used these parameters to fit the proposed theoretical population model. We investigated the patterns in our model to insure we adequately encapsulated the patterns in the data with our model to assess the effects of our parametrisation above. Large-scale ecological experiments are very informative but often need to be interpreted with caution due to often unique problems. We address these below and add additional direction to address these uncertainties in the results we found.

Our population model representation is relatively simplistic compared to some of the previous models that incorporated more interacting species and subsequently complex interactions. Our experimental design was just a big taking advantage of the situation to built a simple population model from CR data. A benefit to a simple BHM model is the ability to use bayes theorem to re-assess additional data in context of the proposed predictions. In the context of the data we have used in this experiment and uninformative priors. We choose to focus on high quality data collection methods and the key dynamics already identified with invasive species dynamics in NZ beech forests. There are however several key aspects that may be confounding our results, to the observational and population model choices.

## Stoat control

An alternative explanation for the lack of any observed effects of stoat control on mouse abundance was that the removal of animals was potentially limited by the effectiveness of a particular stoat control program, management or experimental design.

If trapping did not remove a sufficient number of individual stoats to reduce predation pressure we will not observe the theoretical responses proposed by @tompkins2013 and others.

High individual heterogeneity in the capture rates of stoats at both high and low mouse densities makes reductions to zero individuals virtually impossible targets. This was the case in our study where by-catch of stoats in controlled areas was observed. As an indication of removal, $4.75$ times more stoats were removed from the stoat control program (Hollyford Valley 2001-2004) than caught in by-catch in areas already being controlled prior to the experiment. Our before/after treatment tested this and verified that we did not find differences within the grid when experimental treatments were changed. We may also be missing the impact of by-catch of other pests in stoat traps. We believe that any effect this may have on mice dynamics would be limited due to the limited impacts of rat removal in our data. Biologically, the differences in home range size of rodent species (10's ha; [@bramley2014; @innes1983; @pryde2005]) relative to the home range of stoats and the scale of trap line (100's ha; [@miller2001; @murphy1995]) which suggests that population level impacts from these removals is unlikely due to the limited number of animals removed and the re-invasion biology of rodents [@bramley2014].

**<- is this too critical given ?... ->**

[@blackwell2001; @blackwell2003]: However, the limited geographical scale of the study, low statistical power and replication between different forest types makes it difficult to compare the effect of different treatment types during the four different seasons.

Repleccate and extend on larger scale.
**<- is this too critical given ?... ->**

## Resource pulse systems

During our study we found stoat control had minimal impact on mice populations compared to beech seed. Beech forests have previously defined as *resource pulse systems* [@wardle]. Strong resource pulses cause strong effects throughout an ecosystem [@yang2008]. The process behind for this phenomenon is that even in the absence of control, stoats cannot attain high enough densities to limit mouse populations under conditions of high food availability [@king1983]. Furthermore, the intrinsic differences in the reproductive and growth rates (life history traits) of each species reduces the ability of stoats to regulate mouse populations at the beginning of a masting event[@king2011]. By taking the proposed processes that effect mice dynamics and applying a hierarchical model framework allows us to test and estimate effect sizes that further reduce uncertainty in the outcomes of predator control in NZ beech forests.

The effects of climate change and other human lead impacts will have lasting impacts on on future rodent dynamics [@holland2015]. Population models of climate change indicate a shift to prolonged but lower overall mast events where it may be possible to observe mesopredator release of mice with the removal of predators [@tompkins2013]. Mice populations monitored in more complex forest ecosystems suggest complex interactions between top-down and bottom-up effects [@ruscoe2011; @ruscoe2012]. These studies suggest that rodent populations would increase in other NZ forest ecosystems after the removal of stoats [@ruscoe2011] or other invasive predators [@rayner2007].

## Challanges

Population level responses such as abundance and rate of increase are often measured using indices (e.g. MNA). This can lead to difficulty in estimating population level parameters such as density. We aimed to avoid this bias as we estimated mice abundance using capture-recapture (CR) data and an integrated population model to correctly account for uncertainty in abundance estimation when fitting the population model of mice dynamics. However due to limited population numbers and data, only indices could be used to represent rat interactions. Independent research in beech forests has shown a high correlation between indices of rats in this valley and CR data. Nevertheless, increasing the quality of the rat/kiore data would most likely reduce uncertainty on the estimates of these parameter estimates. By calculating the maximum increase from the fitted population model we were able to compare the maximum population growth rate to other studies ($R.max_{mice} = actual number here$; @hone2010), however,  analogous models are not directly comparable because they do not include a resource component (e.g. beech seed production) or use indices (e.g. $R_{j,t}$). Field studies are also difficult to directly compare because may studies incorporate structurally different ecosystems (e.g @ruscoe2011), species indices instead of true abundance estimation using CR models or did not report effect sizes.  Although this limitations exist our comparisons to general trends were all comparable to our model estimates and our estimates are all biologically viable.

## Management implications

Our model has subtle but important differences compared previous research when in comes to management application. We have incorporated a reproducible workflow[@britishecologicalsociety2018] for the future development of model testing for different and new datasets [@wickham2014]. In doing this we have incorporated leading reproducible science techniques to help address any aspects of our study may need for further support. Often studies of such large scale can address key population-level questions however these studies struggle to find replication because of the scale at which they are conducted [@oksanen2001]. Many issues that many confront a PFNZ2050 will be reduced by using simple but well fitted BHMs for predicting and allocation management resources.

#### Predator-free NZ

Our integrated population modelling approach and the large, high-quality CR data used to parametrise the model allowed us to predict and report the biologically relevant effect sizes. We used this to address the direct question of stoat control in NZ Beech Forests. Future studies can now test and assess the beech forest ecosystem compared to the data they collect. By using the unified modelling framework presented in this paper (Appendix 3; [@davidson2019), reproducible research practises and "tidy-data" [@wickham2014]. Many of the processes we have verified were previously hypothesized using indices of mice abundance [@blackwell2001; @blackwell2003], laboratory experiments [@bridgman2013], novel systems such as remote islands [@mulder2009] and small patches of mainland forest [@blackwell2001; @blackwell2003]. We have integrated these results into a framework that can now test these results in other systems that are hypothesized to be different. It will be important for future work to continue monitoring this system for anomalies and unexpected patterns such as increases in other invasive predators, particularly rats.

